import type { Metadata, Viewport } from 'next'
import { Geist, Geist_Mono, Inter } from 'next/font/google'
import { ReactNode } from 'react'

import { Header } from '@/components/template/header/header'

import '@/assets/style/globals.css'
import { cn } from '@/shared/utils/twMerge'

const inter = Inter({
	subsets: ['latin', 'cyrillic'],
	variable: '--font-sans'
})

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin']
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin']
})

export const viewport: Viewport = {
	width: 'device-width',
	initialScale: 1
	// maximumScale: 1, // Optional: prevents user from zooming
}

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: ReactNode
}>) {
	return (
		<html
			lang='kk'
			className={cn(
				inter.variable,
				geistSans.variable,
				geistMono.variable
			)}
		>
			<body
				className={cn(
					'font-sans antialiased',
					'grid min-h-screen grid-cols-2 grid-rows-[auto_1fr_auto] gap-5 p-5',
					"[grid-template-areas:'header_header''main_main''footer_footer']"
				)}
			>
				<Header className='[grid-area:header]' />

				<main className='[grid-area:main]'>{children}</main>

				<footer className='[grid-area:footer]'>
					<div className='flex justify-center border-t-2 pt-2'>
						Footer. Next pizza
					</div>
				</footer>
			</body>
		</html>
	)
}
